wildfly:
  container_name: wildfly
  build: wildfly/
  ports:
    - 8080:8080 # Port d'exposition
    - 9990:9990 # Port admin
    - 8787:8787 # Port debug
  volumes:
    - ./wildfly/deployments:/opt/jboss/wildfly/standalone/deployments:rw
